version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./todo-backend
    ports:
      - "3002:3002"
    env_file:
      - ./todo-backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./todo-frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:3002
    ports:
      - "3000:3000"
    depends_on:
      - backend
