services:
  todo-frontend:
    build:
      context: ./todo-frontend
      args:
        REACT_APP_BACKEND_URL: http://56.155.38.200:3002/api
    ports:
      - "80:80"
    networks:
      - todo-network
    depends_on:
      - todo-backend

  todo-backend:
    build: ./todo-backend
    ports:
      - "3002:3002"
    env_file:
      - ./todo-backend/.env
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
