version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./todo-backend
    ports:
      - "3002:3002"
    env_file:
      - ./todo-backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://15.207.121.39:3002
    ports:
      - "3000:80"         # ✅ Fix this: maps host 3000 → container nginx port 80
    depends_on:
      - backend



