name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: shubham0039sharma/todos-frontend
      BACKEND_IMAGE: shubham0039sharma/todos-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build React Frontend
        run: |
          docker buildx build --load -t $FRONTEND_IMAGE:latest ./todo-frontend

      - name: Build Node.js Backend
        run: |
          docker buildx build --load -t $BACKEND_IMAGE:latest ./todo-backend

      - name: Push Images to DockerHub
        run: |
          docker push $FRONTEND_IMAGE:latest
          docker push $BACKEND_IMAGE:latest
