name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: shubham0039sharma/todos-frontend
      BACKEND_IMAGE: shubham0039sharma/todos-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE:latest ./todo-frontend

      - name: Build Backend Image
        run: |
          docker build -t $BACKEND_IMAGE:latest ./todo-backend

      - name: Push Images to Docker Hub
        run: |
          docker push $FRONTEND_IMAGE:latest
          docker push $BACKEND_IMAGE:latest
